### ISSUE TITLE
Run to shell script encountered an error

### ISSUE THREAD

**Issue by skeskali** [JenniferMack/Ulysses-post-to-WP#2]
Hi, 

When I tried running this script, I get an error that says: 
"The action “Run Shell Script” encountered an error. Check the actionʼs properties and try running the workflow again." Unfortunately I don't know enough about Automator actions to troubleshoot this. Can you help?  Thanks!

**Comment by JenniferMack** [comment]
I hate to say it, but I’m going to need more information. 
- Did you create the `~/bin` folder in your home folder?
- Did you move the script into that folder without changing it’s name?

The Automator action is just looking for the script. Any actual errors dealing with WP will show up as a notification.

**Comment by skeskali** [comment]
No worries. 😄

I placed the script in the ~/bin folder of my root directory, not the home directory. I did not change the script's name.

Thanks for getting back to me so quickly!
- Cecily

**Comment by JenniferMack** [comment]
Ok, that’s why it can’t be found, the script needs to be in the `~/bin/` folder. I.e. /Users/skeskali/bin, then it should work. The system `/bin` is bad place for personal scripts.

The command `mkdir ~/bin` will do the right thing.

**Comment by skeskali** [comment]
Thanks again. Now I'm getting a different error: "Posting error: wrong size. Was 179, should be 130." The posts are showing up in the WordPress dashboard, but this new error still appears.

Jennifer wrote:

**Comment by JenniferMack** [comment]
Hmm, that’s a WP error now. Try sending just a basic post. Remember the formatting needs to be just like in the README. 

https://github.com/JenniferMack/Ulysses-post-to-WP#ulysses-formatting

**Comment by skeskali** [comment]
Hi, 

It is formatted the same way, but I'm still getting the error. I'll ignore it as long as the posts are being sent to WordPress. 

Thanks again for your help!

Jennifer wrote:

**Comment by JenniferMack** [comment]
Glad it’s working.
