### ISSUE TITLE
Posting Error: Wrong Size, Was 179, Should be 130

### ISSUE THREAD

**Issue by manishsuwal** [JenniferMack/Ulysses-post-to-WP#3]
After using post-to-wordpress app through Ulysses, I get this error message every time.
![screen shot 2015-05-29 at 10 50 57](https://cloud.githubusercontent.com/assets/5318719/7876785/d1ec1482-05f0-11e5-87cd-2ba8416784d6.png)

I think it posts to WordPress irregardless of this message. I remember getting this same error yesterday but the post was published to WordPress.

What does this error message mean?

**Comment by JenniferMack** [comment]
I’m not sure. This has been reported before. I wrote this script to pass WP errors back directly, and this is coming from WP itself. I’ve never seen that error when posting to my site. If you’re interested in trying to track it down, I’ll need more info. 

Things like:
- wp.com or self-hosted (where?)
- wp version
- type of post
- any images involved
- any text formatting

**Comment by manishsuwal** [comment]
@JenniferMack  It's weird that the post I write in Ulysses is published to my WordPress website irregardless of the error message. 

> wp.com or self-hosted (where?)

Self hosted on Dreamhost. Here's my website: http://enwil.com

> wp version

Latest version 4.2.2 (as of 2015 Jun 1st)

> type of post

Standard

> any images involved

No. The images don't matter. At first, for a different post, I kept image and it showed the error. Later, I did it without image, and it still showed the error. 

> any text formatting

No text formatting at all. 

BTW, I am using OSX Yosemite 10.10.3

**Comment by JenniferMack** [comment]
I've searched the WP code base and can't find that error. On WP.com it works w/o error. 

I'm at a loss on this one.

**Comment by manishsuwal** [comment]
I think I need to try this on WP.com as well. I have no idea why it's
showing up.

On Thu, Jun 4, 2015 at 2:44 PM, Jennifer notifications@github.com wrote:

> I've searched the WP code base and can't find that error. On WP.com it
> works w/o error.
> 
> I'm at a loss on this one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JenniferMack/Ulysses-post-to-WP/issues/3#issuecomment-108793710
> .

## 

Manish Suwal 'Enwil'

blog http://enwil.com | website http://manishsuwal.com.np |
facebook account http://www.facebook.com/manishsuwal | facebook page
http://www.facebook.com/pages/Enwilcom/266258376816540?ref=ts | twitter
http://www.twitter.com/manishsuwal | google+
https://plus.google.com/118039990517392424384

**Comment by JenniferMack** [comment]
I still never found out why. Closing this for now.
