### ISSUE TITLE
i received return  400 error code.

### ISSUE THREAD

**Issue by hello4leaf** [JenniferMack/Ulysses-post-to-WP#4]
I am using a free account("https://hello4leaf.wordpress.com") provided by wordpress. 
and when i access to my blog, address is displayed on "https://hello4leaf.wordpress.com/"
and i have change XMLRPC::Client.new_from_hash settings in following

"host" => "https://hello4leaf.wordpress.com",
"user" => "hello4leaf",
"password" => "password---",
"use_ssl" => true,   #change to true if hosted on SSL
"path" => "/xmlrpc.php"

But i received return  400 error code.
What was wrong?

**Comment by JenniferMack** [comment]
Try:
`"host" => "hello4leaf.wordpress.com”,`

The ‘https://' is added by the xmlrpc library.

**Comment by hello4leaf** [comment]
Great!   It works!!!
