### ISSUE TITLE
Ist it possible to add Wordpress sites also?

### ISSUE THREAD

**Issue by dhbdev** [JenniferMack/Ulysses-post-to-WP#5]
Hi Jennifer,

thank you for your script.
I play a while with your script, but I'm not a programmer and I ask myself if it is possible to add sites also with your script?

I see in the Wordpress API reference that there is a parameter "wp.pages" but I didn't get any results if I modified your script.

If you have a tipp I appreciate that.

Thank you and best regards
Andreas

**Comment by JenniferMack** [comment]
I’m going to guess you mean static pages. And yes, I’m sure it’s possible. The WordPress API has that functionality, but that is beyond the scope of this script.

If this is something you’d be interested in, contact me privately and we can discuss a price.
