### ISSUE TITLE
Post error

### ISSUE THREAD

**Issue by ghost** [JenniferMack/Ulysses-post-to-WP#6]
Getting a "Posting error: getaddrinfo: nodename nor servname provided or not known."

Not sure what is happening here.

**Comment by JenniferMack** [comment]
Sounds like you have the server info wrong.

**Comment by ghost** [comment]
I'll take a look at it. Thanks.

**Comment by ghost** [comment]
Ah. Added whole URL instead of the base. It works. Going to close the issue. Thanks for the good work.
