### ISSUE TITLE
Error on subdirectory WP installations

### ISSUE THREAD

**Issue by pxlar8** [JenniferMack/Ulysses-post-to-WP#9]
Great script! I have it working well for a site on domain root, but when I change the "host" line in wp-post.rb to a subdomain installation (eg. "domain.com/subfolder" or "domain.com/subfolder/") I'm getting this error:

> Posting error: getaddrinfo: nodename nor servname provided, or not known

**Comment by JenniferMack** [comment]
The host name is just for the base URL. Set that back to the top level domain (i.e. “www.foo.com”) then add the path var to be everything after the `.com`. So:

`"path" => “/subfolder/xmlrpc.php”`

Also it looks like Ulysses is going to make this a native function. They should be starting beta testing soon.
